#!/bin/bash


###########################################################################
###
### This script creates a serial device, RNDIS and CDC-ECM ethernet gadget
###
###########################################################################

#Sources
# https://github.com/RoganDawes/P4wnP1/blob/master/boot/init_usb.sh
# https://www.collabora.com/news-and-blog/blog/2019/02/18/modern-usb-gadget-on-linux-and-how-to-integrate-it-with-systemd-part-1/

if [ ! -d "/sys/kernel/config/usb_gadget" ]; then
  echo "usb-gadget - Module not loaded!"
  echo "usb-gadget - Inserting now"
  insmod /usr/lib/modules/6.1.99/kernel/drivers/usb/gadget/libcomposite.ko
fi

cd /sys/kernel/config/usb_gadget/

mkdir g1 && cd g1

echo 0x1d6b > idVendor # Linux Foundation
echo 0x104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
echo 0xEF > bDeviceClass
echo 0x02 > bDeviceSubClass
echo 0x01 > bDeviceProtocol
mkdir -p strings/0x409
echo "deadbeef" > strings/0x409/serialnumber
echo "Picocalc and Luckfox" > strings/0x409/manufacturer
echo "Picocalc serial and ethernet device" > strings/0x409/product
mkdir -p configs/c.1/strings/0x409
echo "Config 1: Serial and Network" > configs/c.1/strings/0x409/configuration
echo 250 > configs/c.1/MaxPower

# Create an RNDIS adapter for Windows compatability (must load first for windows to identify drivers)

mkdir -p functions/rndis.usb0
echo "42:63:65:13:34:56" > functions/rndis.usb0/host_addr  # MAC address of Picocalc as it appears on host PC
echo "42:63:65:66:43:21" > functions/rndis.usb0/dev_addr  # MAC address of Picocalc RNDIS ethernet adapter (usb0)

# add OS specific device descriptors to force Windows to load RNDIS drivers
mkdir -p os_desc
echo 1 > os_desc/use
echo 0xbc > os_desc/b_vendor_code
echo MSFT100 > os_desc/qw_sign
mkdir -p functions/rndis.usb0/os_desc/interface.rndis
echo RNDIS > functions/rndis.usb0/os_desc/interface.rndis/compatible_id
echo 5162001 > functions/rndis.usb0/os_desc/interface.rndis/sub_compatible_id
ln -s functions/rndis.usb0 configs/c.1/ # RNDIS on config 1 # RNDIS has to be the first interface on Composite device

#Set up serial adapter
mkdir -p functions/acm.usb0
ln -s functions/acm.usb0 configs/c.1/

# Create a CDC-ECM Ethernet gadget (Better support under linux)

mkdir -p functions/ecm.usb1
echo "48:6f:73:74:50:43" > functions/ecm.usb1/host_addr   # MAC address of Picocalc as it appears on host PC
echo "42:61:64:55:53:42" > functions/ecm.usb1/dev_addr  # MAC address of Picocalc CDC-ECM ethernet adapter (usb1)
ln -s functions/ecm.usb1/ configs/c.1/

ln -s configs/c.1/ os_desc # add config 1 to OS descriptors for rdnis

#Enable gadget
ls /sys/class/udc > UDC

ip link set usb0 up
ip link set usb1 up

echo "usb-gadget - Initialized"

#Serial creates ttyGS0
#systemctl enable getty@ttyGS0.service
#systemctl start getty@ttyGS0.service
#Sources
#https://github.com/RoganDawes/P4wnP1/blob/master/boot/init_usb.sh

